### ISSUE TITLE
region-fg in doom-nord breaks other themes (but not doom-nova)

### ISSUE THREAD

**Issue by rumbletumjum** [hlissner/emacs-doom-themes#171] opened 2018-04-29 03:46 UTC
After 36962d9a13c310ea0bbb23d18b59581ba458710c , if doom-nord is applied, and another doom theme is applied afterwards, the new theme won't load; I did this using counsel, but manually evaluating load-theme on one of the affected themes returns the error `(void-variable region-fg)` if the debugger loads, and the usual `Symbol's value as variable is void: region-fg` in the minibuffer. In my tesitng, the only theme that is not affected is doom-nova.

**Comment by hlissner** [comment] 2018-05-03 00:10
e54e7a0f _may_ have addressed this, by deferring evaluation to post-expansion of the macro. I have been unable to reproduce this issue, so this is a shot in the dark. Give it a try and let me know!

**Comment by hlissner** [comment] 2018-05-04 15:13
I am closing this, because it is a duplicate of #166.

**Closed by hlissner** 2018-05-04 15:13 UTC
Labels: investigating
