### ISSUE TITLE
Cursor disappears inside Org blocks (like source, quote etc)

### ISSUE THREAD

**Issue by mrbig033** [hlissner/emacs-doom-themes#360] opened 2019-11-27 15:52 UTC
### My Environment

- **OS**: MX Linux 18
- **$ uname -r**: 4.19.0-5-amd64
- [dotfiles](https://github.com/mrbig033/dotfiles)
- **i3wm** version 4.13
- [~/.config/i3](https://github.com/mrbig033/dotfiles/blob/master/i3/config)
- **GNU Emacs** 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2019-11-19
- [~/.emacs.d](https://github.com/mrbig033/emacs02)
- **evil Version**: 20191125.1525
- **doom themes Version**: 20191127.358
- **Themes tested**: 
   - doom-dracula
   - doom-solarized-dark
   - doom-gruvbox
   - doom-laserwave
   
### Use-package declaration

``` emacs-lisp
(use-package doom-themes
:ensure t
:config
(load-theme 'doom-dracula t))
```
- [Link](https://github.com/mrbig033/emacs02/blob/master/init.org#doom-themes)

### Issue

On Org Mode blocks, the pointer disappears on blank lines, or after the end of the line. Here's how it looks: https://youtu.be/I-ad_IhmCWM

Also tested in [example](https://orgmode.org/manual/Literal-examples.html) and [quote](https://orgmode.org/manual/Paragraphs.html) blocks. Looks like an issue with blocks in general.

**Comment by hlissner** [comment] 2019-11-28 03:00
This is a duplicate of #342, which was fixed (and the fix reportedly works). As I'm not an Emacs 27 user, I cannot readily test this. If you can identify the problematic faces, please let me know. They can be fixed locally with:

```elisp
(with-eval-after-load 'helm
  (set-face-extend 'helm-selection t))
(with-eval-after-load 'macrostep
  (set-face-extend 'macrostep-expansion-highlight-face t))
```

**Closed** 2020-01-06 01:02 UTC
Labels: duplicate
