### ISSUE TITLE
neotree-root-dir-face used to have a beautiful lighter background ...

### ISSUE THREAD

**Issue by jwintz** [hlissner/emacs-doom-themes#106] opened 2017-08-28 17:13 UTC
... no more.

It was like [that](https://user-images.githubusercontent.com/16498050/28304386-ee30cfd4-6bc9-11e7-8be7-1115fdc4d366.png), but now the background face is identical to the rest of the buffer.

Using `solaire-mode` (which I think is not involved), and `doom-one-theme`.

Maybe we could add `doom-neotree-root-dir-face` to the `defcustom`'s ?

**Comment by jwintz** [comment] 2017-08-28 17:20
However, the code seems right, in `doom-themes-common`:

        (neo-root-dir-face   :foreground strings :background bg-alt :box `(:line-width 4 :color ,bg-alt))

**Comment by hlissner** [comment] 2017-08-29 00:48
Ah, this is an oversight on my part, caused by a recent update where I flip `bg` and `bg-alt`. I'll look into this over the weekend.

**Comment by hlissner** [comment] 2017-09-02 19:46
Just pushed a fix for this, so I'll consider this resolved. Feel free to reopen otherwise.

**Closed by hlissner** 2017-09-02 19:46 UTC
Labels: bug
