### ISSUE TITLE
Emacs lisp docstring too dark in doom-molokai theme

### ISSUE THREAD

**Issue by BenFrankel** [hlissner/emacs-doom-themes#73] opened 2017-06-09 07:06 UTC
It looks like this, on line 108:
![emacs-lisp docstring](http://i.imgur.com/ZOewIyD.png)

It's even worse when flycheck highlights it with a warning: 
![emacs-lisp docstring with warning](http://i.imgur.com/mTZXIxj.png)

The text becomes readable when it's in a marked region, however.

**Comment by BenFrankel** [comment] 2017-06-09 07:49
Along the same lines, I noticed that text becomes black on black in helm find files when simultaneously marked and active.

Before (Makefile is active and unmarked):
![before](http://i.imgur.com/dJ7kYEQ.png)

After (log is active and marked):
![after](http://i.imgur.com/prGUkT4.png)

**Comment by BenFrankel** [comment] 2017-06-09 08:04
It seems that the docstring issue is resolved when solaire-mode is installed alongside the doom-molokai theme. The second issue isn't, though.

**Comment by hlissner** [comment] 2017-06-09 13:55
I've pushed fixes for these issues. Let me know if they persist.

**Comment by BenFrankel** [comment] 2017-06-10 03:16
The second issue is solved, but the first one hasn't changed. It's still unreadable in daemon emacs but ok in non-daemon emacs.

**Comment by hlissner** [comment] 2017-06-10 13:11
Yes, I could reproduce it, and I've found the culprit. It had to do with terminal-emacs translating the 24-bit color of `font-lock-doc-face` to an 8-bit color (for the terminal) incorrectly. A slight change nudged it in the right direction. It should be fixed now.

**Comment by hlissner** [comment] 2017-06-30 16:54
The more I tussle with this issue, the more it seems to not be doom-themes' fault.

There seem to be four scenarios when dealing with daemon Emacs:

1. You start GUI Emacs and use it: `emacs`
2. You start terminal emacs and use it: `emacs -nw`
3. From GUI Emacs you start a server with `(server-start)`, then:
  a. Open a GUI frame with `emacsclient -c`
  b. Or open a tty frame with `emacsclient -nw`
4. You spawn an emacs daemon (`emacs --daemon`) and:
  a. Open a GUI frame with `emacsclient -c`
  b. Or open a tty frame with `emacsclient -nw`

What I've discovered is scenarios 1, 2 and 3a/3b work just fine with doom-themes, but 4a/4b do not.

In 4a/4b new frames seem to forget whether they are tty or a GUI frames, confusing Emacs' theme display engine and causing it to treat all frames as tty frames. Thus, you get 8-bit colors in GUI frames (some 16-bit colors bleed through because I specify no 8-bit fallbacks for them). This is what causes the problems you're seeing.

In any case, to fix this I've had to add something like this to my emacs.d:

```emacs-lisp
(defun my-init-theme (&optional _frame)
  (load-theme 'doom-one t))

(defun my-reload-theme-in-daemon (frame)
  (when (or (daemonp) (not (display-graphic-p)))
    (with-selected-frame frame
      (run-with-timer 0.1 nil #'my-init-theme))))

(add-hook 'after-make-frame-functions #'my-init-theme)
(add-hook 'after-make-frame-functions #'my-reload-theme-in-daemon)

;; for GUI sessions
(my-init-theme)
```

What it does is forcibly reload the theme when a new frame is created from a daemon or in the terminal. It isn't ideal, but it works.

Give that snippet a try and see if that fixes the problem.

**Comment by BenFrankel** [comment] 2017-06-30 21:51
Ah, that does it. Thank you so much! :+1:

**Note**: Any settings that override doom-theme's settings must be put in `my-init-theme` after `(load-theme 'doom-xxx t)` in order for them to take effect. I put some linum-related settings in there.

**Closed** 2017-07-18 20:34 UTC
Labels: bug

**Comment by dmille** [comment] 2020-04-26 19:00
For anyone like myself who's been dealing with this issue, and falls under [workflow scenario 4a](https://github.com/hlissner/emacs-doom-themes/issues/73#issuecomment-312319122) like myself, I finally found a solution which addresses the load-on-every-frame issue by using the solution from [this comment](https://github.com/arcticicestudio/nord-emacs/issues/59#issuecomment-414882071). I hope this helps someone. I for one can now sleep at night.
