### ISSUE TITLE
Incompatible with doom-modeline

### ISSUE THREAD

**Issue by seagle0128** [hlissner/emacs-doom-themes#345] opened 2019-10-22 07:49 UTC
The commit 76517a104e59b33a5a30a39b387266d986f84104 makes `doom-themes` incompatible with `doom-modeline`. The screenshot is below:

![image](https://user-images.githubusercontent.com/140797/67266282-71c47f00-f4e2-11e9-9b15-c106e3d00884.png)

But before the screenshot looks like this:
![image](https://user-images.githubusercontent.com/140797/67266595-28286400-f4e3-11e9-99dc-65015bb6ba9f.png)

I change the face as below.
```elisp
(set-face-attribute 'doom-visual-bell nil
                            :inherit 'mode-line
                            :background (face-foreground 'error)
                            :inverse-video nil)
```

**Comment by hlissner** [comment] 2019-10-22 07:57
This is a duplicate of #339.

**Closed by hlissner** 2019-10-22 07:57 UTC
Labels: duplicate

**Comment by seagle0128** [comment] 2019-10-22 08:11
Oh, sorry! I forgot it after the vacation :-( I should update the screenshots there.
