### ISSUE TITLE
Centaur tabs not displaying icons correctly

### ISSUE THREAD

**Issue by shaunsingh** [hlissner/emacs-doom-themes#620] opened 2021-06-07 23:00 UTC
## What happened?

Sorry to bother you again. After following the instructions here: https://github.com/hlissner/emacs-doom-themes/issues/619, the tabline colors are fixed. However, the icons have disappeared: 

<img width="208" alt="image" src="https://user-images.githubusercontent.com/71196912/121097510-15e76080-c7c2-11eb-9e07-d5cf914ae9c4.png">

## What did you expect to happen?

The tabline should look as it did before the update: 

<img width="289" alt="image" src="https://user-images.githubusercontent.com/71196912/121097613-416a4b00-c7c2-11eb-87f5-7095782b4240.png">

## Steps to reproduce
1. Install Doom emacs, with centaur tabs +icons enabled under `init.el`
2. unpin `doom-themes` in `packages.el`
3. `doom sync -u` and open up a file in emacs 

## System Information
+ Emacs version: emacs-plus@28 with native-comp
+ Emacs distro: Doom Emacs
+ Operating system: MacOS
+ Installed commit of doom-themes: Latest
+ Which theme are you using: doom-nord, although the issue happens with all the themes 

- tested with solarized dark, solarized light, doom-one, as well as doom-moonlight

**Comment by hlissner** [comment] 2021-06-07 23:07
1. This is not an issue for this package, but for Doom Emacs.
2. The `:ui tabs` module does not have an `+icons` flag. Icons are enabled out of the box.
3. I cannot reproduce your issue in vanilla Doom:

   ![image](https://user-images.githubusercontent.com/510883/121098157-44b20680-c7c3-11eb-9e87-533ffb4d95ef.png)

   Therefore it is an issue with your private config. Please double check it.

I will close this since this, but feel free to follow up here.

**Closed by hlissner** 2021-06-07 23:07 UTC
