### ISSUE TITLE
doom-nord differs from original theme

### ISSUE THREAD

**Issue by Linuus** [hlissner/emacs-doom-themes#370] opened 2020-01-04 11:32 UTC
Just a small question. Is doom-nord supposed to look as close to the original emacs-nord theme as possible?

There are quite a few differences right now:

![Screenshot 2020-01-02 at 22 50 51](https://user-images.githubusercontent.com/379823/71764878-181efe80-2eee-11ea-8627-2a1c778fb055.png)
![Screenshot 2020-01-02 at 22 50 44](https://user-images.githubusercontent.com/379823/71764879-1c4b1c00-2eee-11ea-8e4e-dcabe595e2bf.png)

The top one is the original emacs nord theme and the bottom one is doom-nord.

**Comment by ema2159** [comment] 2020-01-04 12:04
It's supposed to use the official pallette! If I remember well I tried to mimic VS Code's implementation. For example, I used a darker modeline because that's how it's done in VS Code

**Comment by Linuus** [comment] 2020-01-04 13:18
I’m mostly concerned about the yellow colors :) I’ve never used VS code but when I look at the screenshots at https://www.nordtheme.com/ports/visual-studio-code it doesn’t look like it’s using the yellow colors either.

**Comment by Linuus** [comment] 2020-01-05 16:37
And I don’t mean that the yellow color is wrong. It just shouldn’t be used for constants :)

**Comment by ema2159** [comment] 2020-01-07 13:02
The color does belong to the official palette. The theme does look right (at least for me) in other modes, the problem is Emacs inflexibility for mode theming, so if I change the colors for the Ruby mode, I would affect the other modes. What do you propose?

**Comment by Linuus** [comment] 2020-01-07 13:17
> The color does belong to the official palette.

Yep! :)

>  The theme does look right (at least for me) in other modes, the problem is Emacs inflexibility for mode theming, so if I change the colors for the Ruby mode, I would affect the other modes. What do you propose?

TBH I don't know that much about theming in emacs :) However, it looks like the official theme is setting the face to `nord7`: https://github.com/arcticicestudio/nord-emacs/blob/develop/nord-theme.el#L165
which is `"#8FBCBB"`: https://github.com/arcticicestudio/nord-emacs/blob/develop/nord-theme.el#L109

So, if we want it to look the same, I guess we need to do the same here? :)

> (Btw, sorry if I'm a little bit slow answering stuff, I'm travelling 😅)

No worries at all :)

**Comment by Linuus** [comment] 2020-01-08 20:41
While checking the nord site, a lot of the colors here are slightly off.

See: https://www.nordtheme.com/docs/colors-and-palettes

With regards to the color set for `type` which in our case is the yellow above, it explicitly says in the Nord docs that Nord7 should be used for that:

> In the context of syntax highlighting it is used for classes, types and primitives.

I went over the colors a bit locally, and adjusted them:


```
   (red        '("#BF616A" "#ff6655" "red"          )) ;; Nord11
   (orange     '("#D08770" "#dd8844" "brightred"    )) ;; Nord12
   (green      '("#A3BE8C" "#99bb66" "green"        )) ;; Nord14
   (teal       '("#8FBCBB" "#44b9b1" "brightgreen"  )) ;; Nord7
   (yellow     '("#EBCB8B" "#ECBE7B" "yellow"       )) ;; Nord13
   (blue       '("#81A1C1" "#51afef" "brightblue"   )) ;; Nord9
   (dark-blue  '("#5E81AC" "#2257A0" "blue"         )) ;; Nord10
   (magenta    '("#B48EAD" "#c678dd" "magenta"      )) ;; Nord15
   (violet     '("#5D80AE" "#a9a1e1" "brightmagenta")) ;; ??
   (cyan       '("#88C0D0" "#46D9FF" "brightcyan"   )) ;; Nord8
   (dark-cyan  '("#507681" "#5699AF" "cyan"         )) ;; ??
```

`violet` and `dark-cyan` has not been changed because I didn't know what color to use in Nord :P 

WDYT about these changes as a start?

Then, the `type` should be set to `teal`:
```
(type           teal)
```

**Comment by ema2159** [comment] 2020-01-08 21:56
I'll check them as soon as I return, but you've seem to have done your work pretty well going through the docs, so I'll try to make those changes as soon as I'm able to.

**Comment by ema2159** [comment] 2020-01-17 16:15
Done. Fixed in 2ec6df8.

**Closed by ema2159** 2020-01-17 16:15 UTC

**Comment by Linuus** [comment] 2020-01-17 17:59
Thanks! I think you mean https://github.com/hlissner/emacs-doom-themes/commit/392f299e793ec78b61aa7bb09f568c400e46b86d though 😊👍

**Comment by ema2159** [comment] 2020-01-17 18:07
Yes, sorry or that! The funny thing is that I think the Nord Palette has changed because the last time I checked the colors from the official website, they were the ones that I was using.
