### ISSUE TITLE
Solarized Light produces unreadable highlighting

### ISSUE THREAD

**Issue by cflewis** [hlissner/emacs-doom-themes#483] opened 2020-06-05 19:15 UTC
Solarized Light colors are configured in such a way that highlights clash with one another, and so text becomes unreadable.

This screenshot is deceptive due to the size that GitHub renders it as. At a normal font size, the text is very hard to read.

![Screenshot from 2020-06-05 12-10-53](https://user-images.githubusercontent.com/43708/83914443-14560900-a726-11ea-9cb7-4a9fde7c3ab3.png)

This one speaks for itself :wink: 

![Screenshot from 2020-06-05 12-11-34](https://user-images.githubusercontent.com/43708/83914447-17e99000-a726-11ea-88a5-ae96c893e346.png)

**Comment by ema2159** [comment] 2020-06-07 17:05
Nice catch. I'll fix it soon!

**Comment by ema2159** [comment] 2020-06-17 23:13
Could you please tell me specifically which faces need to be fixed? Also, are you using MELPA stable?

**Comment by cflewis** [comment] 2020-06-22 17:02
I believe I am using stable (in so much as I haven't changed it from
whatever the default is).

This is what my font is set to:

`(setq doom-font (font-spec :family "PragmataProMonoLiga NF" :size 20))`

**Comment by ema2159** [comment] 2020-06-22 17:43
You shouldn't be using Melpa Stable's version. It hasn't been updated in quite a while. At first I was confused because I didn't saw the errors and the reason is that they were fixed quite some time ago, but in order to see those changes you must use the "normal" Melpa version.

**Comment by cflewis** [comment] 2020-06-22 22:23
Hmm, I am not sure how to do this :( I tried adding this to `packages.el`:

```lisp
(package! emacs-doom-themes
    :recipe (:host github :repo "hlissner/emacs-doom-themes"))
```

but it didn't help at all. I haven't made any modification to the Doom Emacs MELPA settings, and I don't see anything in the config files that reference it.

Am I being silly?

**Comment by ema2159** [comment] 2020-06-23 01:13
No you're not. I don't know either because I don't use Doom. @hlissner how do you use bleeding edge Melpa in Doom?

**Comment by ema2159** [comment] 2020-08-01 00:35
@cflewis did you figure it out? I'll be closing the issue since the problem is not from the theme per se, but from the version you're using. Unfortunately I don't use Doom, so I'm as lost as you with regards to configuring which MELPA use. Just know that that is the issue, so fixing that will also fix the theme for you (and additionally adding a plethora of new, nice and clean, well maintained themes).

**Closed by ema2159** 2020-08-01 00:35 UTC

**Comment by cflewis** [comment] 2020-08-01 00:55
Yeah I didn't make too much progress, but I'm ok with how things are. Sorry for not updating the Issue 😩

**Comment by ema2159** [comment] 2020-08-01 04:04
@cflewis don't worry man! It's not your fault. Is there any way that I can see your config?

**Comment by cflewis** [comment] 2020-08-01 04:05
I am happy to do so, but I've switched work so that now I'm in IntelliJ all day, so this itch isn't something I experience anymore.

Would you still like the configs?
