### ISSUE TITLE
doom-gruvbox: invisible special buffers

### ISSUE THREAD

**Issue by AndreaOrru** [hlissner/emacs-doom-themes#458] opened 2020-05-09 10:02 UTC
![image](https://user-images.githubusercontent.com/3673952/81470783-9df9e000-9227-11ea-868d-7948d6979bc1.png)

That should be `*Messages*`, but the color of the background is the same as the foreground.

**Comment by ema2159** [comment] 2020-05-11 16:27
![image](https://user-images.githubusercontent.com/17773218/81585651-b249f400-9371-11ea-9cb4-014585c13fe4.png)
I'm not sure if it's because of the icons but I can't reproduce, how do you reach that gray state?

**Comment by AndreaOrru** [comment] 2020-05-14 11:57
I don't use Doom Emacs, just a standard Emacs distribution with pretty vanilla Ivy configuration

**Comment by ema2159** [comment] 2020-05-14 14:15
Me neither. I also use vanilla Emacs!

**Comment by AndreaOrru** [comment] 2020-05-14 14:23
Weird. I switched to Tomorrow Night but I'm definitely experiencing this with Gruvbox.

**Comment by ema2159** [comment] 2020-05-14 17:36
Wait a second. You're not using `solaire-mode` am I right? I would encourage you to use it since most of the themes o this package are changed and tweaked with [solaire-mode](https://github.com/hlissner/emacs-solaire-mode) in mind. Also, it improves the looks of your Emacs a lot.

**Comment by ocelaiwo** [comment] 2020-05-15 17:04
I also experience this issue with doom-gruvbox and ivy. It started after I switched to Emacs 27. @AndreaOrru, do you use Emacs 27? Also, as I have just checked, solaire-mode does not help (and also blends the modeline with the buffer).
A similiar thing occurs when using lsp-ui-peek (Screenshot attached - as you can see, `KInstIterator` gets grayed out, which probably should not happen)
![image](https://user-images.githubusercontent.com/57271510/82076956-051c0680-96f8-11ea-9a57-d0340309f00d.png)

**Comment by AndreaOrru** [comment] 2020-05-15 17:52
Yes, I use Emacs 27.

**Comment by ianpan870102** [comment] 2020-05-21 04:20
I am also experiencing this issue. The special buffers (I believe the face is called `ivy-modified-buffer`) is effectively invisible in `doom-gruvbox` only.
If I may, I suggest making the foreground the same color as the comments, and perhaps add a `distant-foreground` for `ivy-current-match`, to boost readability at least a bit.
P.s. I am using Emacs 27 too, but I don't think the version is the cause here.

**Comment by ianpan870102** [comment] 2020-05-26 12:09
This issue can be fixed in my latest PR: https://github.com/hlissner/emacs-doom-themes/pull/475

**Closed** 2020-06-03 02:58 UTC
